[env]
framework = arduino
lib_deps = 
    arduino-libraries/Servo @ ^1.2.1
    https://github.com/nRF24/RF24.git
monitor_speed = 9600

[env:transmitter]
board = 328p16m
platform = atmelavr
upload_port = COM4
build_src_filter = +<*> -<receiver/>

[env:receiver]
board = nano_every
platform = atmelmegaavr
upload_port = COM5
build_src_filter = +<*> -<transmitter/>